# Generated by Django 5.0.6 on 2024-07-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_cartproduct_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
    ]
